export const CONFIG_RECIBO_PADRAO = {
  nomeInstituicao: 'Colégio Júlia',
  subtituloInstituicao: '',
  sigla: 'ESCOLA',
  endereco: '—',
  telefone: '—',
  telefone2: '',
  email: '—',
  logoUrl: null,
  mostrarLogo: true,
  mostrarBancos: false,
  bancos: [],
  tituloPrincipal: 'RECIBO DE PAGAMENTO',
  subtituloPagamento: 'PAGAMENTO DE SERVIÇOS',
  subtituloPropina: 'PROPINAS',
  subtituloMatricula: 'TAXA DE MATRÍCULA',
  subtituloConfirmacao: 'TAXA DE CONFIRMAÇÃO',
  cargoResponsavel: 'SECRETARIA',
  nomeResponsavel: 'RESPONSÁVEL DO SISTEMA',
  textoLegal: 'SISTEMA DE GESTÃO ESCOLAR LUKI © 2026 - Emitido por programa validado nº /AGT',
  rodapeRecibo: '',
  textoViaCopia: 'DUPLICADO - 2ª VIA',
  textoViaOriginal: 'ORIGINAL - 1ª VIA',
};
